django_blog_review/arsenal_players/urls.py
from django.urls import path

from . import views



app_name = "arsenal_players"
urlpatterns = [
    path('', views.index, name="index"),
    path('detail/<int:player_id>/', views.detail, name="detail"),
]

django_blog_review/django_blog_review/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('arsenal_players/', include("arsenal_players.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog_review/arsenal_players/models.py
from django.db import models



class Player(models.Model):
    name             = models.CharField(blank=False, null=False, max_length=100)
    img              = models.ImageField(null=True)
    birth_date       = models.DateField(blank=True)
    introduction     = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.name

django_blog_review/arsenal_players/views.py
from django.shortcuts import render

from .models import Player



def index(request):
    players = Player.objects.all()
    return render(request, "arsenal_players/index.html", {"players": players})

def detail(request, player_id):
    player = Player.objects.get(id=player_id)
    return render(request, "arsenal_players/detail.html", {"player": player})

django_blog_review/arsenal_players/templates/arsenal_players/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<title>選手名鑑</title>
</head>
<body>
	<div class="d-flex justify-content-around my-5">
		<div class="card" style="width: 18rem;">
			<img src="/media/{{ player.img }}" class="card-img-top">
			<div class="card-body">
				<h5 class="card-title">{{ player.name }}</h5>
				<p>{{ player.birth_date }}</p>
				<p class="card-text">{{ player.introduction }}</p>
				<div class="text-end">
					<a class="text-end btn btn-primary" href="{% url 'arsenal_players:index' %}" role="button">戻る</a>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

django_blog_review/arsenal_players/templates/arsenal_players/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<title>選手名鑑</title>
</head>
<body>
	<div class="d-flex justify-content-start flex-wrap mx-5 my-5">
		{% for player in players %}
		<div class="card" style="width: 18rem;">
			<img src="/media/{{ player.img }}" class="card-img-top">
			<div class="card-body">
				<h5 class="card-title">{{ player.name }}</h5>
				<div class="text-end">
					<a href="{% url 'arsenal_players:detail' player_id=player.id %}">詳細情報</a>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</body>
</html>